### ISSUE TITLE
Portfolio boost.

### ISSUE THREAD

**Issue by bukunmialuko** [evergreenx/frontend-blog#1]
In the read me,  add a netlify link for direct access.
Here is a nice resource for fixing issues: https://www.youtube.com/watch?v=WMykv2ZMyEQ&t=621s
Let me know what you think of this issue on whatsapp.

#onelove #develoment #skillimprovement

**Comment by evergreenx** [comment]
@bukunmialuko thanks for the issue. 
I will definitely update the readmd with a live link.
Currently facing some issues hosting the API
